import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { connectToDatabase } from "../db_conn";

export interface Props {
	articles: any;
}

const Home = (props: Props) => {
	console.log("Props: ", props);
	return (
		<div className={styles.container}>
			<Head>
				<title>Stuy Spec TS</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>
		</div>
	);
};

export default Home;

export async function getServerSideProps() {
	const { db } = await connectToDatabase();
	let articles_collection = await db.collection("articles");
	let articles = await articles_collection.find({}).toArray();
	return {
		props: { articles: JSON.stringify(articles) },
	};
}
